version: "3"

services:
  app:
    build: .
    container_name: team_sentry_pages
    restart: always
    env_file:
      - django.env
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 core.wsgi:application"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
